version: "3.9"
services:
  web-app: # Internal port is 8081
    build: web-app
  backend-server:
    build: backend-server
    depends_on:
      - postgres
    environment:
      REST_PORT: 8080
      POSTGRESQL_HOST: postgres
      POSTGRESQL_PORT: 5432
      POSTGRESQL_USER: ${POSTGRES_USER}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESQL_DB: ${POSTGRES_DB}
      MONGO_HOST: mongodb
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
  postgres:
    image: postgres:13.3-alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  mongodb: # For encrypted text documents to allow update only one line
    image: mongo:4.4
    restart: always
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  adminer: # Provides easy to use web interface to manage databases
    image: adminer:4
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "${ADMINER_PORT}:8080"
  prometheus: # Provides easy to use web interface to manage mongodb
    image: prom/prometheus:v2.26.0
    volumes:
      - ./docker-compose/prometheus/:/etc/prometheus/:z # Config files
      - prometheus:/prometheus # Database volume
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    depends_on:
      - backend-server
  grafana:
    image: grafana/grafana:7.5.3
    ports:
      - '${GRAFANA_PORT}:3000'
    volumes: # Use http://prometheus:9090 as connect url for data source
      - ./docker-compose/grafana:/var/lib/grafana:Z # :z is required in SELinux using podman
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USERNAME}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
  traefik: # https://hub.docker.com/_/traefik/
    image: traefik:v2.4.8
    volumes:
      - ./docker-compose/traefik:/etc/traefik:z
    depends_on:
      - backend-server
      - web-app
    ports:
      - 80:80
      - 8092:8080 # Dashboard: http://localhost:8082
volumes:
  prometheus:
  postgres:
  mongodb:
