version: "3.9"
services:
  server-backend:
    build: server-backend
    ports:
      - "8080:8080"
  web-app:
    build: web-app
    ports:
      - "8081:8081"
  prometheus:
    image: prom/prometheus:v2.26.0
    volumes:
      - ./prometheus/:/etc/prometheus/:z # Config files
      - prometheus:/prometheus # Database volume
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    depends_on:
      - server-backend
  grafana:
    image: grafana/grafana:7.5.3
    ports:
      - '3000:3000'
    volumes: # Use http://prometheus:9090 as connect url for data source
      - ./grafana:/var/lib/grafana:Z # :z is required in SELinux using podman
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USERNAME}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
volumes:
  prometheus:
  grafana: