version: "3.9"
services:
  server-backend:
    build: server-backend
    ports:
      - "8080:8080"
  web-app:
    build: web-app
    ports:
      - "8081:8081"
  influxdb:
    image: influxdb:1.8
    ports:
      - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=admin
    networks:
      - influxdb
  grafana:
    image: grafana/grafana:7.5.3
    ports:
      - '3000:3000'
    volumes: # Use http://influxdb:8086 as connect url for data source
      - ./grafana:/var/lib/grafana:z # :z is required in SELinux using podman
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - influxdb
volumes:
  influxdb:
networks:
  influxdb: