global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus' # It's prometheus itself
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'server-backend'
    static_configs:
      - targets: ['server-backend:8080']
